### ISSUE TITLE
Password protect access (apache)

### ISSUE THREAD

**Issue by Nilpferd** [Rudloff/alltube#102] opened 2017-04-15 13:17 UTC
Unable to password protect access using AuthType Basic from apache.

```
<Directory /path_to_alltube/>
  AllowOverride AuthConfig
  AuthType Basic
  AuthName "Password:"
  AuthBasicProvider file
  AuthUserFile /pathtopw/passwords
  AuthGroupFile /pathtopw/groups
  Require group mygroup
</Directory>
```

Logs from apache:
```
PHP Fatal error:  Uncaught InvalidArgumentException: Invalid Hostname, some labels contain invalid characters in [...]/alltube/vendor/league/uri/src/Components/HostnameTrait.php:134
Stack trace:
#0 [...]/alltube/vendor/league/uri/src/Components/HostnameTrait.php(112): League\\Uri\\UriParser->isValidContent(Array)
#1 [...]/alltube/vendor/league/uri/src/Components/HostnameTrait.php(63): League\\Uri\\UriParser->assertValidHost(Array)
#2 [...]/alltube/vendor/league/uri/src/UriParser.php(178): League\\Uri\\UriParser->validateStringHost('mypassword')
#3 [...]/alltube/vendor/league/uri/src/UriParser.php(162): League\\Uri\\UriParser->filterHost('mypassword')
#4 [...]/alltube/vendor/league/uri/src/UriParser.php(142): League\\Uri\\UriParser->parseHostname('mypassword')
#5 [...]/alltube/vendor/league/uri/src/UriParser.php(82): League\\Uri\\UriParser->parseAuthority('//user:mypassword...')
#6 [...]/alltube/vendor/league/uri/src/UriParser.php(67): League\\Uri\\UriParser->parse('https://user:mypassword... in [...]/alltube/vendor/league/uri/src/Components/HostnameTrait.php on line 134
```

tested on latest release.

Cheers

**Comment by Rudloff** [comment] 2017-04-15 17:13
I tried your config but I can't reproduce the bug:
```
pierre@pierre ~/w/alltube> curl "http://foo:bar@localhost/alltube/" -I
HTTP/1.1 200 OK
Date: Sat, 15 Apr 2017 17:11:27 GMT
Server: Apache/2.4.10 (Debian)
Content-Length: 3787
Content-Type: text/html; charset=UTF-8
```

What is the full URL you use to access Alltube?

**Comment by Nilpferd** [comment] 2017-04-15 17:19
I simply use https://alltube.mydomain.eu/

Here the full .conf file:

```
<VirtualHost myip:80>
    ServerAdmin me@mydomain.eu
    ServerName alltube.mydomain.eu

    RewriteEngine on
    ReWriteCond %{HTTPS} off
    RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R]
</VirtualHost>

<VirtualHost myip:443>
    ServerAdmin me@mydomain.eu
    ServerName alltube.mydomain.eu

    ErrorLog logs/alltube.mydomain.eu-error_log
    CustomLog logs/alltube.mydomain.eu-access_log common

    DocumentRoot /path_to_alltube
    <Directory /path_to_alltube/>
        AllowOverride AuthConfig
        AuthType Basic
        AuthName "Password:"
        AuthBasicProvider file
        AuthUserFile /pathtopw/passwords
        AuthGroupFile /pathtopw/groups
        Require group mygroup
    </Directory>


    # Activation du mode SSL
    SSLEngine On
    SSLOptions +FakeBasicAuth +ExportCertData +StrictRequire
    # On indique ou est le certificat
    SSLCertificateFile /path_to_cert/server_cert.pem
    SSLCertificateKeyFile /path_to_key/server_key.pem
</VirtualHost>
```

**Comment by Rudloff** [comment] 2017-04-15 17:42
Hum, even with your exact config, I can't reproduce this issue.
It might be a bug in the [URI](http://uri.thephpleague.com/) library but it's hard to diagnose it without being able to reproduce the bug.

Can you try adding this in `vendor/league/uri/src/UriParser.php`: 
```diff
diff --git a/src/UriParser.php b/src/UriParser.php
index 28f4627..2d2c126 100644
--- a/src/UriParser.php
+++ b/src/UriParser.php
@@ -64,6 +64,8 @@ class UriParser
      */
     public function __invoke($uri)
     {
+        ob_clean();
+        var_dump($uri); die;
         return $this->parse($uri);
     }
```
Then reload Alltube and copy here what is displayed by the page.

**Comment by Nilpferd** [comment] 2017-04-15 17:46
I get string(48) "https://user:password@alltube.mydomain.eu"

note: there is an "@" sign and other special characters in my password, might be the problem, no?

**Comment by Rudloff** [comment] 2017-04-15 17:51
That's really strange because I get the same URL but no error.
I will need to investigate this further.

Are you using the 0.8.0 release?
What operating system are you running Apache on?
Did you install from Git or from the release package?

**Comment by Nilpferd** [comment] 2017-04-15 17:56
Yes 0.8.0 installed from the release package, Ubuntu 16.04 Server 64bit, Apache 2.4.18, PHP 7.0.15

commenting this out removes the error:
```
<Directory /path_to_alltube/>
        AllowOverride AuthConfig
        AuthType Basic
        AuthName "Password:"
        AuthBasicProvider file
        AuthUserFile /pathtopw/passwords
        AuthGroupFile /pathtopw/groups
        Require group mygroup
</Directory>
```

**Comment by Rudloff** [comment] 2017-04-15 18:27
I published a new beta release with an updated URI library: https://github.com/Rudloff/alltube/releases/tag/0.8.1-beta
Can you please try it and tell me if your issue still happens?

**Comment by Nilpferd** [comment] 2017-04-15 20:00
Tried and it still doesn't work; I tried using a different password and then it worked. I can confirm that this is probably due to a special character contained in the previous password...

Don't worry, i'll just use a different password for now :)
Anyhow, thanks a lot for your time!

**Comment by Rudloff** [comment] 2017-04-15 20:18
Inded the issue was caused by an `@` in the password (didn't see your note there).
It's great if you can use a different password but I will try to find a fix when I have some time.

**Comment by Rudloff** [comment] 2017-04-24 22:54
This has been reported upstream: https://github.com/slimphp/Slim/issues/2201

**Comment by Rudloff** [comment] 2017-07-06 10:28
Closing this since #118 fixes it.

**Closed by Rudloff** 2017-07-06 10:28 UTC
Labels: bug
