### ISSUE TITLE
Tiktok error

### ISSUE THREAD

**Issue by mikagrand** [Rudloff/alltube#366] opened 2021-07-10 14:56 UTC
Hello,
TikTok video download not working after clic download button.

url: https://alltubedownload.net/info?url=https%3A%2F%2Fwww.tiktok.com%2F%40hamiltonbrayan%2Fvideo%2F6978156871022857478%3Fsender_device%3Dpc%26sender_web_id%3D6932471844961338885%26is_from_webapp%3Dv1%26is_copy_url%3D0

## Your environment

Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?**

**What is your web server (Apache, IIS, etc.)?**

**What version of AllTube are you using?**

**How did you install AllTube (with Git or with a release package)?**

**What version of PHP are you using?**

**What version of Python are you using?**

**What version of youtube-dl are you using?**

**Do you get any PHP-related errors in your webserver's logs?**

**What is the content of your `config/config.yml` file?**

```yaml
# Insert content here.
```

**Please provide the URL of a video that causes the issue.**

**Comment by Rudloff** [comment] 2021-07-11 14:59
Duplicate of #354

**Closed by Rudloff** 2021-07-11 14:59 UTC
