### ISSUE TITLE
Some videos won't download from YouTube

### ISSUE THREAD

**Issue by viktor02** [Rudloff/alltube#300] opened 2020-07-29 19:00 UTC
# Some videos won't download from YouTube

## Your environment

I use your https://alltubedownload.net

**Please provide the URL of a video that causes the issue.**
https://youtu.be/llmWH99cJBo
https://youtu.be/Bknc2lLj_N4

## Describe your issue
<details>
  <summary>https://youtu.be/Bknc2lLj_N4</summary>
  
![изображение](https://user-images.githubusercontent.com/19672960/88841365-8b6bc300-d1e6-11ea-8c34-baee838253e9.png)

</details>

<details>
  <summary>https://youtu.be/llmWH99cJBo</summary>
  
![изображение](https://user-images.githubusercontent.com/19672960/88841188-3e87ec80-d1e6-11ea-9482-532274379676.png)

</details>

**Comment by Rudloff** [comment] 2020-07-31 10:22
Thanks for the report.

I can't reproduce the issue with https://youtu.be/llmWH99cJBo.

It seems https://youtu.be/Bknc2lLj_N4 fails because it is a restricted video: https://github.com/ytdl-org/youtube-dl/issues/26152

**Comment by psistorm** [comment] 2020-09-23 13:05
Same issue with: https://youtu.be/JlJcFg4ox_s

Might be related to [this issue in yt-dl](https://github.com/ytdl-org/youtube-dl/issues/26152) which was fixed in July. This is a video for kids, might be the issue if not handled correctly on download.

**Comment by Rudloff** [comment] 2020-10-10 21:04
I can't watch https://www.youtube.com/watch?v=JlJcFg4ox_s&feature=youtu.be, it seems to require Youtube Premium

I upgraded youtube-dl on the develop branch and now https://www.youtube.com/watch?v=Bknc2lLj_N4&feature=youtu.be downloads correctly, so I am closing.

**Closed by Rudloff** 2020-10-10 21:04 UTC
Labels: bug

**Comment by psistorm** [comment] 2020-10-11 10:03
Any chance to allow YouTube login and store those cookies for alltube to be able to use this login to download Premium videos as well? Or is this not possible via the YouTube API?

**Comment by Rudloff** [comment] 2020-10-11 10:17
It would theoretically be possible, but it would have to be supported by youtube-dl first.

**Comment by psistorm** [comment] 2020-10-12 13:27
As I see it youtube-dl support it already when I handover a cookies.txt like `youtube-dl --cookies /pathtocookiefile`

**Comment by Rudloff** [comment] 2020-10-13 18:35
What I meant was waiting for youtube-dl to not crash with the URL you gave.
Also, please open a separate issue for this feature request.
