### ISSUE TITLE
wrong ip

### ISSUE THREAD

**Issue by goodoldman** [Rudloff/alltube#39] opened 2015-10-31 02:13 UTC
Hi, great work on this.

Extraction method of direct video url from most sites is correct but lately many sites are starting to restrict the download to the IP that made the request.

For ex: http://allmyvideos.net/h71v2klcew7t
The extracted url looks like this: 
http://d4758.allmyvideos.net/d/yomjxpemyq5dh6ln3temxnmngdz64a2luhrddpxgkdwowo4l36f5elo6e3gw62a/video.mp4?v2
This works only on the IP of the server, but not the client who is trying to download the video.

Is there a way to adapt the script to retrieve the file and serve it to the user from the server automatically?

**Comment by Rudloff** [comment] 2015-10-31 11:00
Hello,

We used to stream the video through the server, but we removed it because it used **a lot** of resources and unnecessarily slowed the downloads down.

You have a few options here:
- Run Alltube locally
- Use [youtube-dl](https://rg3.github.io/youtube-dl/) directly

**Comment by goodoldman** [comment] 2015-10-31 11:36
Thanks Pierre. May I see how that was done? Do you still have the working code for it somewhere?I know running y-dl locally ‎would solve the issue but that's not the point. Alltube is about creating a 'Web interface' for y-dl.  Hence it most likely won't be run locally and will be hosted on a cheap remote server with cheap bandwidth and accessed thru the web (as we do with alltubedownload.com)It sure will consume bandwidth to stream thru the server but the 'option' to do so should still be available for use somehow (perhaps only at backend or maybe like that audio mp3 switch). ‎ I have tested each site in the extraction list one by one; a majority of the sites are now producing ip-restricted download urls; hence rendering the 'web' interface not usable. :s                                                                                                                                                                                                                                                                                                                                                                                                                   From: Pierre RudloffSent: Saturday, 31 October 2015 15:00To: Rudloff/alltubeReply To: Rudloff/alltubeCc: goodoldmanSubject: Re: [alltube] wrong ip (#39)Hello,

We used to stream the video through the server, but we removed it because it used a lot of resources and unnecessarily slowed the downloads down.

You have a few options here:


Run Alltube locally
Use youtube-dl directly


—Reply to this email directly or view it on GitHub.

**Comment by Rudloff** [comment] 2015-10-31 15:35
You can see here how we used to do it: https://github.com/Rudloff/alltube/blob/c9990a208439029f4e0fee0b68512073dbbbc8c7/api.php#L119
We basically set the right headers and used ```readfile()``` on the video URL.

I don't really want to spend time on adding this back as an option but I might accept a pull request.

**Comment by Rudloff** [comment] 2016-04-08 22:49
I started working on a [branch](https://github.com/Rudloff/alltube/tree/feature/stream) that streams the video through the server so we can download IP-restricted videos.
I tried to deploy it on our server but it used way too much resources :disappointed:

**Comment by nodiscc** [comment] 2016-04-08 23:33
Hi

>  I tried to deploy it on our server but it used way too much resources

do you mean it uses too much bandwidth? I had a quick look at the patch (i looked at https://github.com/Rudloff/alltube/compare/master...feature/stream) but I don't think I'm able to understand it. In my view it should be something like

 * actually download the video to the server's disk.
 * create a `<video>` object on the page pointing to that file on the server.

As far as I know this method would only involve eating download+reupload bandwidth on the server  and let the client browser handle decoding? Or maybe you're are you attempting something else.

Thx for your work on alltube (2 years!)

**Comment by Rudloff** [comment] 2016-04-08 23:49
> do you mean it uses too much bandwidth?

The problem is probably the bandwidth yes, but I can't know for sure because we don't have access to these statistics on alltubedownload.net. All I can tell is that after a few minutes, we started to have request timeouts.


> In my view it should be something like
> * actually download the video to the server's disk.
> * create a `<video>` object on the page pointing to that file on the server.

It does not actually download the whole video to the server (because that would use a lot of disk space and would take a long time to start). Instead it reads the video data and streams it immediately chunk by chunk to the browser.

**Comment by Rudloff** [comment] 2017-01-16 11:11
The `feature/stream` branch has been merged into `develop` and you can now enable this functionality by adding `stream: true` to your `config.yml` file.

**Closed by Rudloff** 2017-01-16 11:11 UTC
Labels: enhancement
