### ISSUE TITLE
heroku white page

### ISSUE THREAD

**Issue by iM0hamed** [Rudloff/alltube#263] opened 2020-02-23 12:31 UTC
https://istorebox.herokuapp.com/

its white page only

**Comment by Rudloff** [comment] 2020-02-23 16:04
This is probably similar to #262.
You need to have a look at Heroku logs to see if you can get a specific error message.

**Comment by iM0hamed** [comment] 2020-02-23 18:15
2020-02-23T18:14:07.424789+00:00 app[web.1]: #1 /app/vendor/jawira/case-converter/src/Convert.php(166): Jawira\CaseConverter\Convert->readSnake()
2020-02-23T18:14:07.425021+00:00 app[web.1]: #2 /app/vendor/jawira/case-converter/src/Convert.php(80): Jawira\CaseConverter\Convert->readCamel()
2020-02-23T18:14:07.427474+00:00 app[web.1]: #3 /app/vendor/jawira/case-converter/src/Convert.php(56): Jawira\CaseConverter\Convert->load()
2020-02-23T18:14:07.427694+00:00 app[web.1]: #4 /app/classes/Config.php(242): Jawira\CaseConverter\Convert->__construct()
2020-02-23T18:14:07.427906+00:00 app[web.1]: #5 /app/classes/Config.php(153): Alltube\Config->getEnv()
2020-02-23T18:14:07.428077+00:00 app[web.1]: #6 /app/classes/Config.php(258): Alltube\Config->__construct()
2020-02-23T18:14:07.428224+00:00 app[web.1]: #7 /app/index.php(29): Alltube\Config::getInstance()
2020-02-23T18:14:07.428299+00:00 app[web.1]: #8 {main}
2020-02-23T18:14:07.428493+00:00 app[web.1]:   thrown in /app/vendor/jawira/case-converter/src/Convert.php on line 129
2020-02-23T18:14:07.429053+00:00 app[web.1]: 10.30.238.92 - - [23/Feb/2020:18:14:07 +0000] "GET / HTTP/1.1" 500 - "https://dashboard.heroku.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.*.* Safari/537.36

**Comment by Rudloff** [comment] 2020-02-26 20:39
This is clearly a duplicate of #262.

**Closed by Rudloff** 2020-02-26 20:39 UTC
