### ISSUE TITLE
twitter not work

### ISSUE THREAD

**Issue by bunaif** [Rudloff/alltube#231] opened 2019-06-27 12:19 UTC
why, twitter not work 
example link
https://twitter.com/OracolX/status/1142286738477522944?s=19

error message 
An error occurred

Please check the URL of your video.
ERROR: Unable to download JSON metadata: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by Rudloff** [comment] 2019-06-27 19:38
Hello,
Please don't remove the issue template.

> HTTP Error 429: Too Many Requests

The server was blacklisted because it submitted too many requests to Twitter.

**Comment by KaKi87** [comment] 2019-08-07 18:01
Duplicate of #175 but still relevant today.
I'm experiencing the same 429 error for YouTube...

**Comment by Rudloff** [comment] 2019-08-07 20:28
Unfortunately, we can'd do anything about 429 errors.
The solution here is for people to host their own Alltube instance.

**Closed by Rudloff** 2019-08-07 20:28 UTC
Labels: question
