### ISSUE TITLE
Heroku Build Doesn't Start

### ISSUE THREAD

**Issue by manitaggarwal** [Rudloff/alltube#189] opened 2018-08-30 08:23 UTC
It says that you have not put valid values.
Could you kindly check

**Comment by Rudloff** [comment] 2018-08-30 08:32
Hello,

Did you use the "Deploy to Heroku" button or did you create the Heroku app manually?
You need the `CONVERT` and `PYTHON` config vars to be defined.

**Comment by manitaggarwal** [comment] 2018-08-30 09:00
I used Deploy on Heroku button

**Comment by Rudloff** [comment] 2018-08-30 11:39
`CONVERT` is a boolean, it should either be `true` or `false`, depending on whether you want to enable audio conversion.
`PYTHON` is a string, and you should keep the default (`/app/.heroku/python/bin/python` on Heroku).

If you get an error, could you please copy the exact error here?

**Comment by manitaggarwal** [comment] 2018-08-31 03:33
This is the error I am getting, above mentioned steps. 

'''
Script composer install --ignore-platform-reqs handling the compile event returned with error code 255

 !     ERROR: Compile step failed!
 !     
 !     Installation of dependencies was successful, but the custom
 !     script you're using to perform actions after 'composer install'
 !     failed with the error above.
 !     
 !     Check that the 'compile' command(s) in the 'scripts' section of
 !     your 'composer.json' are working properly and not running into
 !     timeouts or memory limits.
 !     
 !     For more information on the 'composer compile' step, refer to
 !     https://devcenter.heroku.com/articles/php-support

 !     Push rejected, failed to compile PHP app.

 !     Push failed
'''

**Comment by Rudloff** [comment] 2018-08-31 08:41
This has nothing to do with config vars.
The issue is that ffmpeg 4.0 is not available anymore:
```
         - Installing ffmpeg/ffmpeg (4.0): Downloading (failed)
         [Composer\Downloader\TransportException]                                                                                              
         The "https://johnvansickle.com/ffmpeg/releases/ffmpeg-4.0-64bit-static.tar.xz" file could not be downloaded (HTTP/1.1 404 Not Found)  
```

This was recently fixed on develop (https://github.com/Rudloff/alltube/commit/b25b483d41ce8f796ba7f29df45a430763f00f2b) but not on master.

I published a new release with the fix so you can try again and it should work.

**Comment by manitaggarwal** [comment] 2018-08-31 10:31
Worked like a charm.  :-)

**Closed** 2018-08-31 10:31 UTC
Labels: bug
