### ISSUE TITLE
[Help] i can't download some videos !

### ISSUE THREAD

**Issue by yas9999** [Rudloff/alltube#64] opened 2016-08-13 00:42 UTC
Hello @Rudloff ,
i have an issue in downloading some videos ! (i can download the same link with mp3 enabled ! )
this is youtube link example : https://www.youtube.com/watch?v=uxpDa-c-4Mc
it doesn't work also in alltubedownload.net
i guess this part need some fix 

Best regards,

**Comment by Rudloff** [comment] 2016-08-13 10:13
Hello,

This seems to be a duplicate of #56. Youtube added some kind of IP check on Vevo videos and refuses to serve them if the IP address downloading the video is not the same as the IP address running Alltube.

**Comment by yas9999** [comment] 2016-08-13 14:13
hùm so can we just stream those files as you had done with mp3 ?

**Comment by Rudloff** [comment] 2016-08-13 14:19
We already tried (see #39) but we had to disable it because it used too much resources.
If you are hosting your own instance of Alltube, you can try the `feature/stream` branch but it is experimental.

**Comment by yas9999** [comment] 2016-08-17 15:01
hùm, i don't know how to add this option about downloading mp3 i guess they have stream without file extension ! how can i add .mp3 extension at the end of the link ?
http://alltubedownload.net/video?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DYqeW9_5kURI&audio=on

because when i try to make android webview application i can't download but mp4 is working perfectly

**Comment by Rudloff** [comment] 2016-08-17 15:09
Sorry but I don't understand your question.
Are you saying your browser does not recognize the downloaded file as MP3?
It does have the correct MIME type:
```
pierre@quai10 ~> curl -I "http://alltubedownload.net/video?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DYqeW9_5kURI&audio=on" -s | grep Content-Type
Content-Type: audio/mpeg
```

What are you trying to do exactly? (Please provide some code or logs if relevant.)

**Comment by Rudloff** [comment] 2016-08-17 15:10
Also please open a different issue if this is a different problem than the one you originally reported.

**Comment by Rudloff** [comment] 2016-08-17 17:26
Closing as a duplicate of #39.

**Closed by Rudloff** 2016-08-17 17:26 UTC
Labels: duplicate
