### ISSUE TITLE
Streaming returning empty files

### ISSUE THREAD

**Issue by Liandriz** [Rudloff/alltube#134] opened 2017-11-02 17:20 UTC
Following https://github.com/Rudloff/alltube/issues/133 now working, i'm getting videos through the streaming function, working like a charm with some Debian box.
Now, i want to get it to work on some Alpine Linux + nginx, i can get all working for the download links, but for the streaming versions, it only gives me some empty - but well named - files.

Any idea to get it working on Alpine please (already checked the dependencies, seems they're all good to go) ?

**Comment by Rudloff** [comment] 2017-11-02 19:01
Unfortunately, I don't use Alpine or Nginx. But you should probably look at your logs and see if there are any PHP errors there.

**Comment by Liandriz** [comment] 2017-11-02 22:20
No error at all, from PHP, though it was a secondary nginx acting as reverse proxy, but same thing with direct access, empty files. will revert to some Debian for this one i think.

**Comment by Rudloff** [comment] 2017-11-03 08:58
You could also try running Alltube's tests (`./vendor/bin/phpunit`) in order to see what fails exactly.

**Comment by Liandriz** [comment] 2017-11-04 13:54
Weird. Got : 

> Exception: Can't find rtmpdump
/www/alltube/classes/VideoDownload.php:224
/www/alltube/classes/VideoDownload.php:305
/www/alltube/tests/VideoDownloadTest.php:349

It's in vendor + installed systemwide, must be some bash on Alpine misconfig or something.
Will get back to some Debian so, thanks for help.

**Comment by Rudloff** [comment] 2017-11-04 14:01
The binary in `vendor/bin/rtmpdump` is for x86-64 Linux. Is your system 64 bits?
If not, you can try to use the system-wide binary by setting this in `config/config.yml`:
```yaml
rtmpdump: /path/to/rtmpdump
```

**Comment by Liandriz** [comment] 2017-11-06 21:06
Already tried all the path available, in vendor/ and system-installed package. 
Feels like this is some Alpine bash problem. And yes, x64 container.

**Comment by Rudloff** [comment] 2017-11-10 22:41
Since it seems the issue is not caused by Alltube, I'm closing.
Please feel free to reopen if you need more info.

**Closed by Rudloff** 2017-11-10 22:41 UTC
Labels: question
