### ISSUE TITLE
Different video format gotten from website and as library.

### ISSUE THREAD

**Issue by kinglyl** [Rudloff/alltube#260] opened 2020-02-12 15:08 UTC
# Different video format gotten from website and as library.

## Your environment
Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?**
`Ubuntu 18.04 LTS`
**What is your web server (Apache, IIS, etc.)?**
`Apache2`
**What version of AllTube are you using?**
`LTS by 2020-02-12`
**How did you install AllTube (with Git or with a release package)?**
`Git`
**What version of PHP are you using?**
`7.2.24`
**What version of Python are you using?**
`3.6.9`
**What version of youtube-dl are you using?**
`2020.01.01`
**Do you get any PHP-related errors in your webserver's logs?**
*no*
**What is the content of your `config/config.yml` file?**
```yml
---
# Path to your youtube-dl binary
youtubedl: vendor/rg3/youtube-dl/youtube_dl/__main__.py

# Path to your python binary
python: /usr/bin/python3

# An array of parameters to pass to youtube-dl
params:
    - --no-warnings
    - --ignore-errors
    - --flat-playlist
    - --restrict-filenames
    - --no-playlist

# True to enable audio conversion
convert: true

# True to enable advanced conversion mode
convertAdvanced: true

# List of formats available in advanced conversion mode
convertAdvancedFormats: [mp3, avi, flv, wav]

# Path to your avconv or ffmpeg binary
avconv: vendor/bin/ffmpeg

# avconv/ffmpeg logging level.
avconvVerbosity: error

# Path to the directory that contains the phantomjs binary.
phantomjsDir: vendor/bin/

# True to disable URL rewriting
uglyUrls: false

# True to stream videos through server
stream: true

# True to enable remux mode (merge best audio and best video)
remux: true

# MP3 bitrate when converting (in kbit/s)
audioBitrate: 128

# App name
appName: AllTube Download

# Generic formats supported by youtube-dl
genericFormats:
    best: Best
    bestvideo+bestaudio: Remux best video with best audio
    worst: Worst
```

## Describe your issue
I use Alltube as a libaray to get pornhub videos .
But recently I found that when I get a pornhub video by website(Alltube website I bulit),I can get a 'mp4' file, but I can only get 'm3u8' file while using it as a function.

my Alltube website:
https://52proxy.fun/ytb/

**Comment by kinglyl** [comment] 2020-02-13 08:42
When I use Alltube as a library.I use this options
```
Config::setOptions(
    [
        'youtubedl' => '/usr/local/bin/youtube-dl',
		'python' 	=> '/usr/bin/python3',
		'params'	=> array("--no-warnings","--ignore-errors","--flat-playlist","--restrict-filenames","--no-playlist"),
		
    ]
);
```

And I try to get specific videos by using 
```
$video = new Video($url, 'mp4');
```

**Comment by kinglyl** [comment] 2020-02-14 08:07
I found an interesting fact.
If I use **Alltube website JSON API** to get json, the url will be a mp4 file
But if I use function ``getJson()`` , I will get m3u8 file

**Comment by Rudloff** [comment] 2020-02-15 09:14
Hello,
Would it be possible to provide a SFW video that reproduces the issue?

M3U8 is not a real video format, it is a playlist format that only contains references to video files located elsewhere. There is usually no point in just downloading the M3U8 file by itself, so if stream mode is enabled, Alltube will fetch the real video stream for you: https://github.com/Rudloff/alltube/blob/acc63a536e72709f8d8043b06652e3a92ddb10bb/controllers/DownloadController.php#L167
So if you want to do the same thing with the library, you probably need to use `getM3uStream()`.

**Comment by kinglyl** [comment] 2020-02-15 10:41
I will provide the url later, but I think I have fixed how to get a mp4 url
`-f mp4` is not right. It should be `-f 720p`

**Comment by kinglyl** [comment] 2020-02-15 10:42
About providing a SFW video, I just found the problem on pornhub by now...

**Comment by sam9177** [comment] 2020-02-17 21:22
> I will provide the url later, but I think I have fixed how to get a mp4 url
> `-f mp4` is not right. It should be `-f 720p`

Hello,
Where to put '-f 720p' to get 720p link?
With default settings it shows link to .m3u8

**Comment by kinglyl** [comment] 2020-02-18 00:49
> > I will provide the url later, but I think I have fixed how to get a mp4 url
> > `-f mp4` is not right. It should be `-f 720p`
> 
> Hello,
> Where to put '-f 720p' to get 720p link?
> With default settings it shows link to .m3u8

like this
```php
$video = new Video($url, "720p");
```

**Comment by sam9177** [comment] 2020-02-18 07:59
> > > I will provide the url later, but I think I have fixed how to get a mp4 url
> > > `-f mp4` is not right. It should be `-f 720p`
> > 
> > 
> > Hello,
> > Where to put '-f 720p' to get 720p link?
> > With default settings it shows link to .m3u8
> 
> like this
> 
> ```
> $video = new Video($url, "720p");
> ```

Thank you, it works.

For youtube-dl I can use '[height<=720]' command.
youtube-dl -g -f '[height<=720]' URL
This command will give a link no higher than 720p resolution

For example if video have 1080p it will show 720p
If 720p -> 720p
If 480p -> 480p

How can I use this command?

**Comment by kinglyl** [comment] 2020-02-18 11:21
> > > > I will provide the url later, but I think I have fixed how to get a mp4 url
> > > > `-f mp4` is not right. It should be `-f 720p`
> > > 
> > > 
> > > Hello,
> > > Where to put '-f 720p' to get 720p link?
> > > With default settings it shows link to .m3u8
> > 
> > 
> > like this
> > ```
> > $video = new Video($url, "720p");
> > ```
> 
> Thank you, it works.
> 
> For youtube-dl I can use '[height<=720]' command.
> youtube-dl -g -f '[height<=720]' URL
> This command will give a link no higher than 720p resolution
> 
> For example if video have 1080p it will show 720p
> If 720p -> 720p
> If 480p -> 480p
> 
> How can I use this command or something like this?

According to the code, I found that you can use `$video = new Video($url, "[height<=720]")` , because
```php
$video = new Video($url, $format);
$video_url = $video->getUrl();
``` 
will run as
```bash
youtube-dl -g -f $format $url
```

May be it will be better if @Rudloff  will be so nice to add more information in README

**Comment by sam9177** [comment] 2020-02-18 18:10
Thank you!

**Comment by sam9177** [comment] 2020-02-18 18:52
Thank you!

**Comment by Rudloff** [comment] 2020-03-19 08:58
I am closing this, since it seems you got what you needed.

**Closed by Rudloff** 2020-03-19 08:58 UTC
