### ISSUE TITLE
AllTube Downloads Only  First Video Of Pornhub Playlist Videos

### ISSUE THREAD

**Issue by Rainyjour** [Rudloff/alltube#67] opened 2016-09-07 12:28 UTC
Unfortunately AllTube Downloads Only First Video Of Pornhub Playlist Videos, not rest ones :(

**Comment by Rudloff** [comment] 2016-09-07 12:30
Closing as a duplicate of https://github.com/Rudloff/alltube/issues/58.
Alltube currently does not download any playlist.

**Closed** 2016-09-08 21:59 UTC
Labels: duplicate
