### ISSUE TITLE
Update youtube-dl

### ISSUE THREAD

**Issue by JTTM** [Rudloff/alltube#220] opened 2019-04-28 02:45 UTC
Hi. There is an extraction bug in the previous version of youtube-dl.
https://github.com/ytdl-org/youtube-dl/issues/20758
> Something Went Wrong
> ERROR: 2BVbyCZXc5s: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. 

The latest version fixes that. Please update youtube-dl to 2019.04.24. Thanks!
https://github.com/ytdl-org/youtube-dl/releases/tag/2019.04.24

**Comment by Rudloff** [comment] 2019-04-28 11:46
Duplicate of https://github.com/Rudloff/alltube/issues/219.

**Closed by Rudloff** 2019-04-28 11:46 UTC
Labels: duplicate

**Comment by JTTM** [comment] 2019-04-28 11:51
Thanks! I didn't check the closed issues.
