### ISSUE TITLE
Alltube multiple downloads at once?

### ISSUE THREAD

**Issue by nahventure** [Rudloff/alltube#236] opened 2019-07-17 20:37 UTC
# New issue
Allowing multiple streams at once
## Your environment
Ubuntu 18.04
Please answer these questions when reporting a new issue:

**What is your operating system (Windows, Linux, OSX, etc.)?**

**What is your web server (Apache, IIS, etc.)?**
Apache 2.4.29
**What version of AllTube are you using?**
Latest
**How did you install AllTube (with Git or with a release package)?**
rp
**What version of PHP are you using?**
7.2
**What version of Python are you using?**
3.x
**What version of youtube-dl are you using?**
latest

## Describe your issue
I can't seem to let multiple users use my service with streaming enabled. It just loads until the user downloading finishes allowing for a new request. Would it be possible to have multiple processes? I have enough ram and CPU to do it all, although it seems like a software limitation. I can provide more information as needed.

**Comment by Rudloff** [comment] 2019-08-20 21:15
Hello,
I can't reproduce this issue and I am pretty sure that https://alltubedownload.net/ has multiple users downloading at the same time.
This is probably a problem with your Apache settings, you might need to add more Apache processes.

**Comment by nahventure** [comment] 2019-08-20 22:17
Could you point me in the right direction? For adding more Apache
processes. I am using php-fpm for my major projects so I am unsure of how
to do this.

**Comment by nahventure** [comment] 2019-08-20 22:20
Upon further investigation, could I be looking at MPM for this? Or am
I missing something?

**Comment by Rudloff** [comment] 2019-09-15 09:50
If you are using php-fpm, there could be 2 different bottlenecks :
* You can set the number of PHP procesess in your php-fpm configuration.
* You can set the number of Apache processes in your Apache MPM configuration.

**Comment by Rudloff** [comment] 2020-05-14 08:47
No answer so I'm closing.
Feel free to reopen if you still have a problem.

**Closed by Rudloff** 2020-05-14 08:47 UTC
