### ISSUE TITLE
How can I down video to NAS directly rather then broswer,I really think it's very useful!

### ISSUE THREAD

**Issue by amColinzzz** [Rudloff/alltube#266] opened 2020-03-17 20:10 UTC
# New issue

## Your environment

CentOS 8 in docker.Because I am user in docker,So i del follow item questations.

**What is your operating system (Windows, Linux, OSX, etc.)?**
CentOS

## Describe your issue
I am very like this web-ui,but it's only support download by browser ,so if it's also can download video directly to the server self,Then i can user NAS SMB server share the video.it will be very useful!!! I really whish author can add this .

**Comment by Rudloff** [comment] 2020-03-17 20:16
Duplicate of #179

**Closed by Rudloff** 2020-03-17 20:16 UTC
