### ISSUE TITLE
500 Internal Error

### ISSUE THREAD

**Issue by aidinzolghadr** [Rudloff/alltube#87] opened 2017-01-07 04:11 UTC
Hi,

I have a linux server that I have wordpress on it's root. Tried alltube but it gives me 500 Internal Error. set permission to 777 and 775 on template_c and then all files, no change. I can't change AllowOverride  on the Apache as my host doesn't allow it.

Any luck?

Thanks

**Comment by Rudloff** [comment] 2017-01-07 09:39
Hello,
Can you please provide Apache error logs?

**Comment by aidinzolghadr** [comment] 2017-01-08 21:47
Sorry I'm not proficient with terminal or php.

I've been googling your question for two days and this is what I came up with:

I created a php.ini file and put this in it:

error_reporting = E_ALL | E_STRICT
log_errors = On
display_errors = Off
error_log = /parent_dir/alltube

and put that file inside the alltube directory to make it generate error logs (I've read this is the way to get php log files).

There is a "logs" directory on root of my web space but I cannot find any file that seem related to alltube. I could find a access.log.current file that I think is the most related thing in the logs directory of my root and the only thing I could find related to alltube was a request:

47.24.23.31 - - [08/Jan/2017:16:28:31 -0500] "GET /temp/alltube/index.php HTTP/1.1" 404 - mydomain.com "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:49.0) Gecko/20100101 Firefox/49.0" "-"

But the lines after it are unrelated, like some robots crawling my site and like that.

I also could not set AllowOverride to anything, since my server is shared, but I think it is enabled because I can have .htaccess files and they work.

If you be more precise on what do you want me to do, I'll be more than happy to provide info.

Thanks.

**Comment by aidinzolghadr** [comment] 2017-01-08 22:16
I think problem is with the .htaccess file because when I deleted it, alltube site came up but it didn't download and returned an error nor the extractors link work, same error.

**Comment by aidinzolghadr** [comment] 2017-01-08 22:20
Are these two lines OK?

```
Redirect permanent /api.php /video
Redirect permanent /extractors.php /extractors
```

I checked with two online htaccess tester and both returned error for these two lines saying: This redirect was not followed.

**Comment by aidinzolghadr** [comment] 2017-01-08 22:23
Maybe because those two files do not exists?

**Comment by Rudloff** [comment] 2017-01-08 22:28
These are legacy redirect rules that can be safely ignored. They can cause a warning but certainly not a 500 error.
The error is probably caused by one of the lines in `.htaccess` calling an Apache module that isn't available on your server.

Can you try with this minimal `.htaccess` file please: 
```
RewriteEngine On

RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ index.php [QSA,L]
```

**Comment by aidinzolghadr** [comment] 2017-01-08 22:31
Shows my WordPress "Page not found" page. I have a WordPress site that I made a folder for alltube inside it and unzipped the release file into it and running from there.

**Comment by Rudloff** [comment] 2017-01-08 22:42
That's strange, the WordPress redirect should not be triggered if the folder does exist.
I can't reproduce this behavior with my WordPress.

What if you explicitely call index.php (http://example.com/alltube/index.php)?

**Comment by aidinzolghadr** [comment] 2017-01-08 22:45
Same 500 error.

**Comment by aidinzolghadr** [comment] 2017-01-08 22:47
I also changed permissions a lot as I searched and apparently it can cause error 500 as well. No luck. Changed all files to 644 and folders to 755, no luck, everything to 755, same thing.

I also did not install via npm as I can't install npm on my server as I don't have root access.

**Comment by Rudloff** [comment] 2017-01-08 23:00
In the folder where you found the access.log file, is there also an error.log file? This would be way easier to debug with the log file.

**Comment by aidinzolghadr** [comment] 2017-01-09 00:50
No there is no such file there, I even searched my whole home directory with:

`find ~/ f -name "error.log"
`

**Comment by Rudloff** [comment] 2017-01-09 09:12
I'm sorry but I can't help you without knowing the exact error. You should ask your hosting provider how to get the error logs.
(It seems rather strange to me that you have an access log but not an error log.)

**Comment by aidinzolghadr** [comment] 2017-01-10 08:30
I'm trying to find it, as the support is non existent. Please note that I ran rapidleech once on this server and it is written in PHP as well and worked fine, just like the WordPress that is currently running and is in PHP as well.

**Comment by aidinzolghadr** [comment] 2017-01-10 08:42
I think I've enabled php error reporting correctly but since it doesn't make a log file, I think it's because error is not php related as I think it's about that ".htaccess" file that is causing the problem.

**Comment by aidinzolghadr** [comment] 2017-01-10 08:45
Also on 7.1 release note you said it should be used on Python on Heroku, I don't know if it's the case with us.

**Comment by Rudloff** [comment] 2017-01-10 09:25
If the error is caused by the .htacces, it is not a PHP error so PHP error reporting won't help you.
You need to see the Apache error log and I can't help you without this error.

However, I am working on an option to disable .htaccess/URL rewriting (#88) so this might help you.

**Comment by aidinzolghadr** [comment] 2017-01-10 20:23
Thanks. I've spent a lot of time today to investigate this and can't find Apache's error log files, just regular logs that what requested what from the site.

But I tried to comment/uncomment every line from the .htaccess file and as it turns out, there are two lines that causes problem here (or my server has problems with):

`RewriteRule ^ index.php [QSA,L]`

This line causes the "Page Not Found" error (while the other problematic line is commented)

And the 2nd line is:
`AddOutputFilterByType DEFLATE text/css text/html application/javascript font/truetype`

Which causes the error 500.

Putting php_flag was causing the 500 error as well so I removed it.

I've seen people having problems with RewriteRule in my host (1and1) and putting a slash before the file name solved their problem, sadly not in my case.

**Comment by aidinzolghadr** [comment] 2017-01-10 22:21
I also run PHP 5.5, does your program needs a higher version of PHP?

**Comment by aidinzolghadr** [comment] 2017-01-10 22:59
It runs!

A question though, when I press download, it opens up the file in my browser, isn't it supposed to download it to my host? Isn't it calling youtube-dl in the background?

**Comment by aidinzolghadr** [comment] 2017-01-10 23:21
A couple things:

1) Also where can we see list of downloaded files?

2) Bookmarklet is broken. I changed the directory after I ran it first, so it may be it. It has the URL two times like domain/directory/domain/directory?rest_of_stuff

3) Bookmarklet opened an https which my site is http.

4) Any way to batch download URLs? Like setting one quality and it downloads all with that quality.

5) Any way to download youtube playlists?

**Comment by Rudloff** [comment] 2017-01-10 23:34
1: Alltube's purpose is to download videos in the browser, not to the server.
2-3: The bookmarklet is indeed broken. I will fix it for the next release but you can probably easily edit the bookmark yourself.
4: This is not supported.
5: Playlists are not yet supported (see #58).

**Comment by Rudloff** [comment] 2017-02-08 19:24
No answer for a month, closing.

**Closed by Rudloff** 2017-02-08 19:24 UTC
Labels: question
